export interface Emoji {
    name: string,
    char: string,
}

export const emojiData: Emoji[] = [
    {
        name: "100",
        char: "💯"
    }, {
        name: "1234",
        char: "🔢"
    }, {
        name: "umbrella_with_rain_drops",
        char: "☔"
    }, {
        name: "coffee",
        char: "☕"
    }, {
        name: "aries",
        char: "♈"
    }, {
        name: "taurus",
        char: "♉"
    }, {
        name: "sagittarius",
        char: "♐"
    }, {
        name: "capricorn",
        char: "♑"
    }, {
        name: "aquarius",
        char: "♒"
    }, {
        name: "pisces",
        char: "♓"
    }, {
        name: "anchor",
        char: "⚓"
    }, {
        name: "white_check_mark",
        char: "✅"
    }, {
        name: "sparkles",
        char: "✨"
    }, {
        name: "question",
        char: "❓"
    }, {
        name: "grey_question",
        char: "❔"
    }, {
        name: "grey_exclamation",
        char: "❕"
    }, {
        name: "exclamation",
        char: "❗"
    }, {
        name: "heavy_exclamation_mark",
        char: "❗"
    }, {
        name: "heavy_plus_sign",
        char: "➕"
    }, {
        name: "heavy_minus_sign",
        char: "➖"
    }, {
        name: "heavy_division_sign",
        char: "➗"
    }, {
        name: "hash",
        char: "#️⃣"
    }, {
        name: "keycap_star",
        char: "*️⃣"
    }, {
        name: "zero",
        char: "0️⃣"
    }, {
        name: "one",
        char: "1️⃣"
    }, {
        name: "two",
        char: "2️⃣"
    }, {
        name: "three",
        char: "3️⃣"
    }, {
        name: "four",
        char: "4️⃣"
    }, {
        name: "five",
        char: "5️⃣"
    }, {
        name: "six",
        char: "6️⃣"
    }, {
        name: "seven",
        char: "7️⃣"
    }, {
        name: "eight",
        char: "8️⃣"
    }, {
        name: "nine",
        char: "9️⃣"
    }, {
        name: "copyright",
        char: "©️"
    }, {
        name: "registered",
        char: "®️"
    }, {
        name: "mahjong",
        char: "🀄"
    }, {
        name: "black_joker",
        char: "🃏"
    }, {
        name: "a",
        char: "🅰️"
    }, {
        name: "b",
        char: "🅱️"
    }, {
        name: "o2",
        char: "🅾️"
    }, {
        name: "parking",
        char: "🅿️"
    }, {
        name: "ab",
        char: "🆎"
    }, {
        name: "cl",
        char: "🆑"
    }, {
        name: "cool",
        char: "🆒"
    }, {
        name: "free",
        char: "🆓"
    }, {
        name: "id",
        char: "🆔"
    }, {
        name: "new",
        char: "🆕"
    }, {
        name: "ng",
        char: "🆖"
    }, {
        name: "ok",
        char: "🆗"
    }, {
        name: "sos",
        char: "🆘"
    }, {
        name: "up",
        char: "🆙"
    }, {
        name: "vs",
        char: "🆚"
    }, {
        name: "flag-ac",
        char: "🇦🇨"
    }, {
        name: "flag-ad",
        char: "🇦🇩"
    }, {
        name: "flag-ae",
        char: "🇦🇪"
    }, {
        name: "flag-af",
        char: "🇦🇫"
    }, {
        name: "flag-ag",
        char: "🇦🇬"
    }, {
        name: "flag-ai",
        char: "🇦🇮"
    }, {
        name: "flag-al",
        char: "🇦🇱"
    }, {
        name: "flag-am",
        char: "🇦🇲"
    }, {
        name: "flag-ao",
        char: "🇦🇴"
    }, {
        name: "flag-aq",
        char: "🇦🇶"
    }, {
        name: "flag-ar",
        char: "🇦🇷"
    }, {
        name: "flag-as",
        char: "🇦🇸"
    }, {
        name: "flag-at",
        char: "🇦🇹"
    }, {
        name: "flag-au",
        char: "🇦🇺"
    }, {
        name: "flag-aw",
        char: "🇦🇼"
    }, {
        name: "flag-ax",
        char: "🇦🇽"
    }, {
        name: "flag-az",
        char: "🇦🇿"
    }, {
        name: "flag-ba",
        char: "🇧🇦"
    }, {
        name: "flag-bb",
        char: "🇧🇧"
    }, {
        name: "flag-bd",
        char: "🇧🇩"
    }, {
        name: "flag-be",
        char: "🇧🇪"
    }, {
        name: "flag-bf",
        char: "🇧🇫"
    }, {
        name: "flag-bg",
        char: "🇧🇬"
    }, {
        name: "flag-bh",
        char: "🇧🇭"
    }, {
        name: "flag-bi",
        char: "🇧🇮"
    }, {
        name: "flag-bj",
        char: "🇧🇯"
    }, {
        name: "flag-bl",
        char: "🇧🇱"
    }, {
        name: "flag-bm",
        char: "🇧🇲"
    }, {
        name: "flag-bn",
        char: "🇧🇳"
    }, {
        name: "flag-bo",
        char: "🇧🇴"
    }, {
        name: "flag-bq",
        char: "🇧🇶"
    }, {
        name: "flag-br",
        char: "🇧🇷"
    }, {
        name: "flag-bs",
        char: "🇧🇸"
    }, {
        name: "flag-bt",
        char: "🇧🇹"
    }, {
        name: "flag-bv",
        char: "🇧🇻"
    }, {
        name: "flag-bw",
        char: "🇧🇼"
    }, {
        name: "flag-by",
        char: "🇧🇾"
    }, {
        name: "flag-bz",
        char: "🇧🇿"
    }, {
        name: "flag-ca",
        char: "🇨🇦"
    }, {
        name: "flag-cc",
        char: "🇨🇨"
    }, {
        name: "flag-cd",
        char: "🇨🇩"
    }, {
        name: "flag-cf",
        char: "🇨🇫"
    }, {
        name: "flag-cg",
        char: "🇨🇬"
    }, {
        name: "flag-ch",
        char: "🇨🇭"
    }, {
        name: "flag-ci",
        char: "🇨🇮"
    }, {
        name: "flag-ck",
        char: "🇨🇰"
    }, {
        name: "flag-cl",
        char: "🇨🇱"
    }, {
        name: "flag-cm",
        char: "🇨🇲"
    }, {
        name: "cn",
        char: "🇨🇳"
    }, {
        name: "flag-cn",
        char: "🇨🇳"
    }, {
        name: "flag-co",
        char: "🇨🇴"
    }, {
        name: "flag-cp",
        char: "🇨🇵"
    }, {
        name: "flag-cr",
        char: "🇨🇷"
    }, {
        name: "flag-cu",
        char: "🇨🇺"
    }, {
        name: "flag-cv",
        char: "🇨🇻"
    }, {
        name: "flag-cw",
        char: "🇨🇼"
    }, {
        name: "flag-cx",
        char: "🇨🇽"
    }, {
        name: "flag-cy",
        char: "🇨🇾"
    }, {
        name: "flag-cz",
        char: "🇨🇿"
    }, {
        name: "de",
        char: "🇩🇪"
    }, {
        name: "flag-de",
        char: "🇩🇪"
    }, {
        name: "flag-dg",
        char: "🇩🇬"
    }, {
        name: "flag-dj",
        char: "🇩🇯"
    }, {
        name: "flag-dk",
        char: "🇩🇰"
    }, {
        name: "flag-dm",
        char: "🇩🇲"
    }, {
        name: "flag-do",
        char: "🇩🇴"
    }, {
        name: "flag-dz",
        char: "🇩🇿"
    }, {
        name: "flag-ea",
        char: "🇪🇦"
    }, {
        name: "flag-ec",
        char: "🇪🇨"
    }, {
        name: "flag-ee",
        char: "🇪🇪"
    }, {
        name: "flag-eg",
        char: "🇪🇬"
    }, {
        name: "flag-eh",
        char: "🇪🇭"
    }, {
        name: "flag-er",
        char: "🇪🇷"
    }, {
        name: "es",
        char: "🇪🇸"
    }, {
        name: "flag-es",
        char: "🇪🇸"
    }, {
        name: "flag-et",
        char: "🇪🇹"
    }, {
        name: "flag-eu",
        char: "🇪🇺"
    }, {
        name: "flag-fi",
        char: "🇫🇮"
    }, {
        name: "flag-fj",
        char: "🇫🇯"
    }, {
        name: "flag-fk",
        char: "🇫🇰"
    }, {
        name: "flag-fm",
        char: "🇫🇲"
    }, {
        name: "flag-fo",
        char: "🇫🇴"
    }, {
        name: "fr",
        char: "🇫🇷"
    }, {
        name: "flag-fr",
        char: "🇫🇷"
    }, {
        name: "flag-ga",
        char: "🇬🇦"
    }, {
        name: "gb",
        char: "🇬🇧"
    }, {
        name: "uk",
        char: "🇬🇧"
    }, {
        name: "flag-gb",
        char: "🇬🇧"
    }, {
        name: "flag-gd",
        char: "🇬🇩"
    }, {
        name: "flag-ge",
        char: "🇬🇪"
    }, {
        name: "flag-gf",
        char: "🇬🇫"
    }, {
        name: "flag-gg",
        char: "🇬🇬"
    }, {
        name: "flag-gh",
        char: "🇬🇭"
    }, {
        name: "flag-gi",
        char: "🇬🇮"
    }, {
        name: "flag-gl",
        char: "🇬🇱"
    }, {
        name: "flag-gm",
        char: "🇬🇲"
    }, {
        name: "flag-gn",
        char: "🇬🇳"
    }, {
        name: "flag-gp",
        char: "🇬🇵"
    }, {
        name: "flag-gq",
        char: "🇬🇶"
    }, {
        name: "flag-gr",
        char: "🇬🇷"
    }, {
        name: "flag-gs",
        char: "🇬🇸"
    }, {
        name: "flag-gt",
        char: "🇬🇹"
    }, {
        name: "flag-gu",
        char: "🇬🇺"
    }, {
        name: "flag-gw",
        char: "🇬🇼"
    }, {
        name: "flag-gy",
        char: "🇬🇾"
    }, {
        name: "flag-hk",
        char: "🇭🇰"
    }, {
        name: "flag-hm",
        char: "🇭🇲"
    }, {
        name: "flag-hn",
        char: "🇭🇳"
    }, {
        name: "flag-hr",
        char: "🇭🇷"
    }, {
        name: "flag-ht",
        char: "🇭🇹"
    }, {
        name: "flag-hu",
        char: "🇭🇺"
    }, {
        name: "flag-ic",
        char: "🇮🇨"
    }, {
        name: "flag-id",
        char: "🇮🇩"
    }, {
        name: "flag-ie",
        char: "🇮🇪"
    }, {
        name: "flag-il",
        char: "🇮🇱"
    }, {
        name: "flag-im",
        char: "🇮🇲"
    }, {
        name: "flag-in",
        char: "🇮🇳"
    }, {
        name: "flag-io",
        char: "🇮🇴"
    }, {
        name: "flag-iq",
        char: "🇮🇶"
    }, {
        name: "flag-ir",
        char: "🇮🇷"
    }, {
        name: "flag-is",
        char: "🇮🇸"
    }, {
        name: "it",
        char: "🇮🇹"
    }, {
        name: "flag-it",
        char: "🇮🇹"
    }, {
        name: "flag-je",
        char: "🇯🇪"
    }, {
        name: "flag-jm",
        char: "🇯🇲"
    }, {
        name: "flag-jo",
        char: "🇯🇴"
    }, {
        name: "jp",
        char: "🇯🇵"
    }, {
        name: "flag-jp",
        char: "🇯🇵"
    }, {
        name: "flag-ke",
        char: "🇰🇪"
    }, {
        name: "flag-kg",
        char: "🇰🇬"
    }, {
        name: "flag-kh",
        char: "🇰🇭"
    }, {
        name: "flag-ki",
        char: "🇰🇮"
    }, {
        name: "flag-km",
        char: "🇰🇲"
    }, {
        name: "flag-kn",
        char: "🇰🇳"
    }, {
        name: "flag-kp",
        char: "🇰🇵"
    }, {
        name: "kr",
        char: "🇰🇷"
    }, {
        name: "flag-kr",
        char: "🇰🇷"
    }, {
        name: "flag-kw",
        char: "🇰🇼"
    }, {
        name: "flag-ky",
        char: "🇰🇾"
    }, {
        name: "flag-kz",
        char: "🇰🇿"
    }, {
        name: "flag-la",
        char: "🇱🇦"
    }, {
        name: "flag-lb",
        char: "🇱🇧"
    }, {
        name: "flag-lc",
        char: "🇱🇨"
    }, {
        name: "flag-li",
        char: "🇱🇮"
    }, {
        name: "flag-lk",
        char: "🇱🇰"
    }, {
        name: "flag-lr",
        char: "🇱🇷"
    }, {
        name: "flag-ls",
        char: "🇱🇸"
    }, {
        name: "flag-lt",
        char: "🇱🇹"
    }, {
        name: "flag-lu",
        char: "🇱🇺"
    }, {
        name: "flag-lv",
        char: "🇱🇻"
    }, {
        name: "flag-ly",
        char: "🇱🇾"
    }, {
        name: "flag-ma",
        char: "🇲🇦"
    }, {
        name: "flag-mc",
        char: "🇲🇨"
    }, {
        name: "flag-md",
        char: "🇲🇩"
    }, {
        name: "flag-me",
        char: "🇲🇪"
    }, {
        name: "flag-mf",
        char: "🇲🇫"
    }, {
        name: "flag-mg",
        char: "🇲🇬"
    }, {
        name: "flag-mh",
        char: "🇲🇭"
    }, {
        name: "flag-mk",
        char: "🇲🇰"
    }, {
        name: "flag-ml",
        char: "🇲🇱"
    }, {
        name: "flag-mm",
        char: "🇲🇲"
    }, {
        name: "flag-mn",
        char: "🇲🇳"
    }, {
        name: "flag-mo",
        char: "🇲🇴"
    }, {
        name: "flag-mp",
        char: "🇲🇵"
    }, {
        name: "flag-mq",
        char: "🇲🇶"
    }, {
        name: "flag-mr",
        char: "🇲🇷"
    }, {
        name: "flag-ms",
        char: "🇲🇸"
    }, {
        name: "flag-mt",
        char: "🇲🇹"
    }, {
        name: "flag-mu",
        char: "🇲🇺"
    }, {
        name: "flag-mv",
        char: "🇲🇻"
    }, {
        name: "flag-mw",
        char: "🇲🇼"
    }, {
        name: "flag-mx",
        char: "🇲🇽"
    }, {
        name: "flag-my",
        char: "🇲🇾"
    }, {
        name: "flag-mz",
        char: "🇲🇿"
    }, {
        name: "flag-na",
        char: "🇳🇦"
    }, {
        name: "flag-nc",
        char: "🇳🇨"
    }, {
        name: "flag-ne",
        char: "🇳🇪"
    }, {
        name: "flag-nf",
        char: "🇳🇫"
    }, {
        name: "flag-ng",
        char: "🇳🇬"
    }, {
        name: "flag-ni",
        char: "🇳🇮"
    }, {
        name: "flag-nl",
        char: "🇳🇱"
    }, {
        name: "flag-no",
        char: "🇳🇴"
    }, {
        name: "flag-np",
        char: "🇳🇵"
    }, {
        name: "flag-nr",
        char: "🇳🇷"
    }, {
        name: "flag-nu",
        char: "🇳🇺"
    }, {
        name: "flag-nz",
        char: "🇳🇿"
    }, {
        name: "flag-om",
        char: "🇴🇲"
    }, {
        name: "flag-pa",
        char: "🇵🇦"
    }, {
        name: "flag-pe",
        char: "🇵🇪"
    }, {
        name: "flag-pf",
        char: "🇵🇫"
    }, {
        name: "flag-pg",
        char: "🇵🇬"
    }, {
        name: "flag-ph",
        char: "🇵🇭"
    }, {
        name: "flag-pk",
        char: "🇵🇰"
    }, {
        name: "flag-pl",
        char: "🇵🇱"
    }, {
        name: "flag-pm",
        char: "🇵🇲"
    }, {
        name: "flag-pn",
        char: "🇵🇳"
    }, {
        name: "flag-pr",
        char: "🇵🇷"
    }, {
        name: "flag-ps",
        char: "🇵🇸"
    }, {
        name: "flag-pt",
        char: "🇵🇹"
    }, {
        name: "flag-pw",
        char: "🇵🇼"
    }, {
        name: "flag-py",
        char: "🇵🇾"
    }, {
        name: "flag-qa",
        char: "🇶🇦"
    }, {
        name: "flag-re",
        char: "🇷🇪"
    }, {
        name: "flag-ro",
        char: "🇷🇴"
    }, {
        name: "flag-rs",
        char: "🇷🇸"
    }, {
        name: "ru",
        char: "🇷🇺"
    }, {
        name: "flag-ru",
        char: "🇷🇺"
    }, {
        name: "flag-rw",
        char: "🇷🇼"
    }, {
        name: "flag-sa",
        char: "🇸🇦"
    }, {
        name: "flag-sb",
        char: "🇸🇧"
    }, {
        name: "flag-sc",
        char: "🇸🇨"
    }, {
        name: "flag-sd",
        char: "🇸🇩"
    }, {
        name: "flag-se",
        char: "🇸🇪"
    }, {
        name: "flag-sg",
        char: "🇸🇬"
    }, {
        name: "flag-sh",
        char: "🇸🇭"
    }, {
        name: "flag-si",
        char: "🇸🇮"
    }, {
        name: "flag-sj",
        char: "🇸🇯"
    }, {
        name: "flag-sk",
        char: "🇸🇰"
    }, {
        name: "flag-sl",
        char: "🇸🇱"
    }, {
        name: "flag-sm",
        char: "🇸🇲"
    }, {
        name: "flag-sn",
        char: "🇸🇳"
    }, {
        name: "flag-so",
        char: "🇸🇴"
    }, {
        name: "flag-sr",
        char: "🇸🇷"
    }, {
        name: "flag-ss",
        char: "🇸🇸"
    }, {
        name: "flag-st",
        char: "🇸🇹"
    }, {
        name: "flag-sv",
        char: "🇸🇻"
    }, {
        name: "flag-sx",
        char: "🇸🇽"
    }, {
        name: "flag-sy",
        char: "🇸🇾"
    }, {
        name: "flag-sz",
        char: "🇸🇿"
    }, {
        name: "flag-ta",
        char: "🇹🇦"
    }, {
        name: "flag-tc",
        char: "🇹🇨"
    }, {
        name: "flag-td",
        char: "🇹🇩"
    }, {
        name: "flag-tf",
        char: "🇹🇫"
    }, {
        name: "flag-tg",
        char: "🇹🇬"
    }, {
        name: "flag-th",
        char: "🇹🇭"
    }, {
        name: "flag-tj",
        char: "🇹🇯"
    }, {
        name: "flag-tk",
        char: "🇹🇰"
    }, {
        name: "flag-tl",
        char: "🇹🇱"
    }, {
        name: "flag-tm",
        char: "🇹🇲"
    }, {
        name: "flag-tn",
        char: "🇹🇳"
    }, {
        name: "flag-to",
        char: "🇹🇴"
    }, {
        name: "flag-tr",
        char: "🇹🇷"
    }, {
        name: "flag-tt",
        char: "🇹🇹"
    }, {
        name: "flag-tv",
        char: "🇹🇻"
    }, {
        name: "flag-tw",
        char: "🇹🇼"
    }, {
        name: "flag-tz",
        char: "🇹🇿"
    }, {
        name: "flag-ua",
        char: "🇺🇦"
    }, {
        name: "flag-ug",
        char: "🇺🇬"
    }, {
        name: "flag-um",
        char: "🇺🇲"
    }, {
        name: "flag-un",
        char: "🇺🇳"
    }, {
        name: "us",
        char: "🇺🇸"
    }, {
        name: "flag-us",
        char: "🇺🇸"
    }, {
        name: "flag-uy",
        char: "🇺🇾"
    }, {
        name: "flag-uz",
        char: "🇺🇿"
    }, {
        name: "flag-va",
        char: "🇻🇦"
    }, {
        name: "flag-vc",
        char: "🇻🇨"
    }, {
        name: "flag-ve",
        char: "🇻🇪"
    }, {
        name: "flag-vg",
        char: "🇻🇬"
    }, {
        name: "flag-vi",
        char: "🇻🇮"
    }, {
        name: "flag-vn",
        char: "🇻🇳"
    }, {
        name: "flag-vu",
        char: "🇻🇺"
    }, {
        name: "flag-wf",
        char: "🇼🇫"
    }, {
        name: "flag-ws",
        char: "🇼🇸"
    }, {
        name: "flag-xk",
        char: "🇽🇰"
    }, {
        name: "flag-ye",
        char: "🇾🇪"
    }, {
        name: "flag-yt",
        char: "🇾🇹"
    }, {
        name: "flag-za",
        char: "🇿🇦"
    }, {
        name: "flag-zm",
        char: "🇿🇲"
    }, {
        name: "flag-zw",
        char: "🇿🇼"
    }, {
        name: "koko",
        char: "🈁"
    }, {
        name: "sa",
        char: "🈂️"
    }, {
        name: "u7121",
        char: "🈚"
    }, {
        name: "u6307",
        char: "🈯"
    }, {
        name: "u7981",
        char: "🈲"
    }, {
        name: "u7a7a",
        char: "🈳"
    }, {
        name: "u5408",
        char: "🈴"
    }, {
        name: "u6e80",
        char: "🈵"
    }, {
        name: "u6709",
        char: "🈶"
    }, {
        name: "u6708",
        char: "🈷️"
    }, {
        name: "u7533",
        char: "🈸"
    }, {
        name: "u5272",
        char: "🈹"
    }, {
        name: "u55b6",
        char: "🈺"
    }, {
        name: "ideograph_advantage",
        char: "🉐"
    }, {
        name: "accept",
        char: "🉑"
    }, {
        name: "cyclone",
        char: "🌀"
    }, {
        name: "foggy",
        char: "🌁"
    }, {
        name: "closed_umbrella",
        char: "🌂"
    }, {
        name: "night_with_stars",
        char: "🌃"
    }, {
        name: "sunrise_over_mountains",
        char: "🌄"
    }, {
        name: "sunrise",
        char: "🌅"
    }, {
        name: "city_sunset",
        char: "🌆"
    }, {
        name: "city_sunrise",
        char: "🌇"
    }, {
        name: "rainbow",
        char: "🌈"
    }, {
        name: "bridge_at_night",
        char: "🌉"
    }, {
        name: "ocean",
        char: "🌊"
    }, {
        name: "volcano",
        char: "🌋"
    }, {
        name: "milky_way",
        char: "🌌"
    }, {
        name: "earth_africa",
        char: "🌍"
    }, {
        name: "earth_americas",
        char: "🌎"
    }, {
        name: "earth_asia",
        char: "🌏"
    }, {
        name: "globe_with_meridians",
        char: "🌐"
    }, {
        name: "new_moon",
        char: "🌑"
    }, {
        name: "waxing_crescent_moon",
        char: "🌒"
    }, {
        name: "first_quarter_moon",
        char: "🌓"
    }, {
        name: "moon",
        char: "🌔"
    }, {
        name: "waxing_gibbous_moon",
        char: "🌔"
    }, {
        name: "full_moon",
        char: "🌕"
    }, {
        name: "waning_gibbous_moon",
        char: "🌖"
    }, {
        name: "last_quarter_moon",
        char: "🌗"
    }, {
        name: "waning_crescent_moon",
        char: "🌘"
    }, {
        name: "crescent_moon",
        char: "🌙"
    }, {
        name: "new_moon_with_face",
        char: "🌚"
    }, {
        name: "first_quarter_moon_with_face",
        char: "🌛"
    }, {
        name: "last_quarter_moon_with_face",
        char: "🌜"
    }, {
        name: "full_moon_with_face",
        char: "🌝"
    }, {
        name: "sun_with_face",
        char: "🌞"
    }, {
        name: "star2",
        char: "🌟"
    }, {
        name: "stars",
        char: "🌠"
    }, {
        name: "thermometer",
        char: "🌡️"
    }, {
        name: "mostly_sunny",
        char: "🌤️"
    }, {
        name: "sun_small_cloud",
        char: "🌤️"
    }, {
        name: "barely_sunny",
        char: "🌥️"
    }, {
        name: "sun_behind_cloud",
        char: "🌥️"
    }, {
        name: "partly_sunny_rain",
        char: "🌦️"
    }, {
        name: "sun_behind_rain_cloud",
        char: "🌦️"
    }, {
        name: "rain_cloud",
        char: "🌧️"
    }, {
        name: "snow_cloud",
        char: "🌨️"
    }, {
        name: "lightning",
        char: "🌩️"
    }, {
        name: "lightning_cloud",
        char: "🌩️"
    }, {
        name: "tornado",
        char: "🌪️"
    }, {
        name: "tornado_cloud",
        char: "🌪️"
    }, {
        name: "fog",
        char: "🌫️"
    }, {
        name: "wind_blowing_face",
        char: "🌬️"
    }, {
        name: "hotdog",
        char: "🌭"
    }, {
        name: "taco",
        char: "🌮"
    }, {
        name: "burrito",
        char: "🌯"
    }, {
        name: "chestnut",
        char: "🌰"
    }, {
        name: "seedling",
        char: "🌱"
    }, {
        name: "evergreen_tree",
        char: "🌲"
    }, {
        name: "deciduous_tree",
        char: "🌳"
    }, {
        name: "palm_tree",
        char: "🌴"
    }, {
        name: "cactus",
        char: "🌵"
    }, {
        name: "hot_pepper",
        char: "🌶️"
    }, {
        name: "tulip",
        char: "🌷"
    }, {
        name: "cherry_blossom",
        char: "🌸"
    }, {
        name: "rose",
        char: "🌹"
    }, {
        name: "hibiscus",
        char: "🌺"
    }, {
        name: "sunflower",
        char: "🌻"
    }, {
        name: "blossom",
        char: "🌼"
    }, {
        name: "corn",
        char: "🌽"
    }, {
        name: "ear_of_rice",
        char: "🌾"
    }, {
        name: "herb",
        char: "🌿"
    }, {
        name: "four_leaf_clover",
        char: "🍀"
    }, {
        name: "maple_leaf",
        char: "🍁"
    }, {
        name: "fallen_leaf",
        char: "🍂"
    }, {
        name: "leaves",
        char: "🍃"
    }, {
        name: "mushroom",
        char: "🍄"
    }, {
        name: "tomato",
        char: "🍅"
    }, {
        name: "eggplant",
        char: "🍆"
    }, {
        name: "grapes",
        char: "🍇"
    }, {
        name: "melon",
        char: "🍈"
    }, {
        name: "watermelon",
        char: "🍉"
    }, {
        name: "tangerine",
        char: "🍊"
    }, {
        name: "lemon",
        char: "🍋"
    }, {
        name: "banana",
        char: "🍌"
    }, {
        name: "pineapple",
        char: "🍍"
    }, {
        name: "apple",
        char: "🍎"
    }, {
        name: "green_apple",
        char: "🍏"
    }, {
        name: "pear",
        char: "🍐"
    }, {
        name: "peach",
        char: "🍑"
    }, {
        name: "cherries",
        char: "🍒"
    }, {
        name: "strawberry",
        char: "🍓"
    }, {
        name: "hamburger",
        char: "🍔"
    }, {
        name: "pizza",
        char: "🍕"
    }, {
        name: "meat_on_bone",
        char: "🍖"
    }, {
        name: "poultry_leg",
        char: "🍗"
    }, {
        name: "rice_cracker",
        char: "🍘"
    }, {
        name: "rice_ball",
        char: "🍙"
    }, {
        name: "rice",
        char: "🍚"
    }, {
        name: "curry",
        char: "🍛"
    }, {
        name: "ramen",
        char: "🍜"
    }, {
        name: "spaghetti",
        char: "🍝"
    }, {
        name: "bread",
        char: "🍞"
    }, {
        name: "fries",
        char: "🍟"
    }, {
        name: "sweet_potato",
        char: "🍠"
    }, {
        name: "dango",
        char: "🍡"
    }, {
        name: "oden",
        char: "🍢"
    }, {
        name: "sushi",
        char: "🍣"
    }, {
        name: "fried_shrimp",
        char: "🍤"
    }, {
        name: "fish_cake",
        char: "🍥"
    }, {
        name: "icecream",
        char: "🍦"
    }, {
        name: "shaved_ice",
        char: "🍧"
    }, {
        name: "ice_cream",
        char: "🍨"
    }, {
        name: "doughnut",
        char: "🍩"
    }, {
        name: "cookie",
        char: "🍪"
    }, {
        name: "chocolate_bar",
        char: "🍫"
    }, {
        name: "candy",
        char: "🍬"
    }, {
        name: "lollipop",
        char: "🍭"
    }, {
        name: "custard",
        char: "🍮"
    }, {
        name: "honey_pot",
        char: "🍯"
    }, {
        name: "cake",
        char: "🍰"
    }, {
        name: "bento",
        char: "🍱"
    }, {
        name: "stew",
        char: "🍲"
    }, {
        name: "fried_egg",
        char: "🍳"
    }, {
        name: "cooking",
        char: "🍳"
    }, {
        name: "fork_and_knife",
        char: "🍴"
    }, {
        name: "tea",
        char: "🍵"
    }, {
        name: "sake",
        char: "🍶"
    }, {
        name: "wine_glass",
        char: "🍷"
    }, {
        name: "cocktail",
        char: "🍸"
    }, {
        name: "tropical_drink",
        char: "🍹"
    }, {
        name: "beer",
        char: "🍺"
    }, {
        name: "beers",
        char: "🍻"
    }, {
        name: "baby_bottle",
        char: "🍼"
    }, {
        name: "knife_fork_plate",
        char: "🍽️"
    }, {
        name: "champagne",
        char: "🍾"
    }, {
        name: "popcorn",
        char: "🍿"
    }, {
        name: "ribbon",
        char: "🎀"
    }, {
        name: "gift",
        char: "🎁"
    }, {
        name: "birthday",
        char: "🎂"
    }, {
        name: "jack_o_lantern",
        char: "🎃"
    }, {
        name: "christmas_tree",
        char: "🎄"
    }, {
        name: "santa",
        char: "🎅"
    }, {
        name: "fireworks",
        char: "🎆"
    }, {
        name: "sparkler",
        char: "🎇"
    }, {
        name: "balloon",
        char: "🎈"
    }, {
        name: "tada",
        char: "🎉"
    }, {
        name: "confetti_ball",
        char: "🎊"
    }, {
        name: "tanabata_tree",
        char: "🎋"
    }, {
        name: "crossed_flags",
        char: "🎌"
    }, {
        name: "bamboo",
        char: "🎍"
    }, {
        name: "dolls",
        char: "🎎"
    }, {
        name: "flags",
        char: "🎏"
    }, {
        name: "wind_chime",
        char: "🎐"
    }, {
        name: "rice_scene",
        char: "🎑"
    }, {
        name: "school_satchel",
        char: "🎒"
    }, {
        name: "mortar_board",
        char: "🎓"
    }, {
        name: "medal",
        char: "🎖️"
    }, {
        name: "reminder_ribbon",
        char: "🎗️"
    }, {
        name: "studio_microphone",
        char: "🎙️"
    }, {
        name: "level_slider",
        char: "🎚️"
    }, {
        name: "control_knobs",
        char: "🎛️"
    }, {
        name: "film_frames",
        char: "🎞️"
    }, {
        name: "admission_tickets",
        char: "🎟️"
    }, {
        name: "carousel_horse",
        char: "🎠"
    }, {
        name: "ferris_wheel",
        char: "🎡"
    }, {
        name: "roller_coaster",
        char: "🎢"
    }, {
        name: "fishing_pole_and_fish",
        char: "🎣"
    }, {
        name: "microphone",
        char: "🎤"
    }, {
        name: "movie_camera",
        char: "🎥"
    }, {
        name: "cinema",
        char: "🎦"
    }, {
        name: "headphones",
        char: "🎧"
    }, {
        name: "art",
        char: "🎨"
    }, {
        name: "tophat",
        char: "🎩"
    }, {
        name: "circus_tent",
        char: "🎪"
    }, {
        name: "ticket",
        char: "🎫"
    }, {
        name: "clapper",
        char: "🎬"
    }, {
        name: "performing_arts",
        char: "🎭"
    }, {
        name: "video_game",
        char: "🎮"
    }, {
        name: "dart",
        char: "🎯"
    }, {
        name: "slot_machine",
        char: "🎰"
    }, {
        name: "8ball",
        char: "🎱"
    }, {
        name: "game_die",
        char: "🎲"
    }, {
        name: "bowling",
        char: "🎳"
    }, {
        name: "flower_playing_cards",
        char: "🎴"
    }, {
        name: "musical_note",
        char: "🎵"
    }, {
        name: "notes",
        char: "🎶"
    }, {
        name: "saxophone",
        char: "🎷"
    }, {
        name: "guitar",
        char: "🎸"
    }, {
        name: "musical_keyboard",
        char: "🎹"
    }, {
        name: "trumpet",
        char: "🎺"
    }, {
        name: "violin",
        char: "🎻"
    }, {
        name: "musical_score",
        char: "🎼"
    }, {
        name: "running_shirt_with_sash",
        char: "🎽"
    }, {
        name: "tennis",
        char: "🎾"
    }, {
        name: "ski",
        char: "🎿"
    }, {
        name: "basketball",
        char: "🏀"
    }, {
        name: "checkered_flag",
        char: "🏁"
    }, {
        name: "snowboarder",
        char: "🏂"
    }, {
        name: "woman-running",
        char: "🏃‍♀️"
    }, {
        name: "man-running",
        char: "🏃‍♂️"
    },
    {
        name: "runner",
        char: "🏃‍♂️"
    }, {
        name: "running",
        char: "🏃‍♂️"
    }, {
        name: "woman-surfing",
        char: "🏄‍♀️"
    }, {
        name: "man-surfing",
        char: "🏄‍♂️"
    }, {
        name: "surfer",
        char: "🏄‍♂️"
    }, {
        name: "sports_medal",
        char: "🏅"
    }, {
        name: "trophy",
        char: "🏆"
    }, {
        name: "horse_racing",
        char: "🏇"
    }, {
        name: "football",
        char: "🏈"
    }, {
        name: "rugby_football",
        char: "🏉"
    }, {
        name: "woman-swimming",
        char: "🏊‍♀️"
    }, {
        name: "man-swimming",
        char: "🏊‍♂️"
    }, {
        name: "swimmer",
        char: "🏊‍♂️"
    }, {
        name: "woman-lifting-weights",
        char: "🏋️‍♀️"
    }, {
        name: "man-lifting-weights",
        char: "🏋️‍♂️"
    }, {
        name: "weight_lifter",
        char: "🏋️‍♂️"
    }, {
        name: "woman-golfing",
        char: "🏌️‍♀️"
    }, {
        name: "man-golfing",
        char: "🏌️‍♂️"
    }, {
        name: "golfer",
        char: "🏌️‍♂️"
    }, {
        name: "racing_motorcycle",
        char: "🏍️"
    }, {
        name: "racing_car",
        char: "🏎️"
    }, {
        name: "cricket_bat_and_ball",
        char: "🏏"
    }, {
        name: "volleyball",
        char: "🏐"
    }, {
        name: "field_hockey_stick_and_ball",
        char: "🏑"
    }, {
        name: "ice_hockey_stick_and_puck",
        char: "🏒"
    }, {
        name: "table_tennis_paddle_and_ball",
        char: "🏓"
    }, {
        name: "snow_capped_mountain",
        char: "🏔️"
    }, {
        name: "camping",
        char: "🏕️"
    }, {
        name: "beach_with_umbrella",
        char: "🏖️"
    }, {
        name: "building_construction",
        char: "🏗️"
    }, {
        name: "house_buildings",
        char: "🏘️"
    }, {
        name: "cityscape",
        char: "🏙️"
    }, {
        name: "derelict_house_building",
        char: "🏚️"
    }, {
        name: "classical_building",
        char: "🏛️"
    }, {
        name: "desert",
        char: "🏜️"
    }, {
        name: "desert_island",
        char: "🏝️"
    }, {
        name: "national_park",
        char: "🏞️"
    }, {
        name: "stadium",
        char: "🏟️"
    }, {
        name: "house",
        char: "🏠"
    }, {
        name: "house_with_garden",
        char: "🏡"
    }, {
        name: "office",
        char: "🏢"
    }, {
        name: "post_office",
        char: "🏣"
    }, {
        name: "european_post_office",
        char: "🏤"
    }, {
        name: "hospital",
        char: "🏥"
    }, {
        name: "bank",
        char: "🏦"
    }, {
        name: "atm",
        char: "🏧"
    }, {
        name: "hotel",
        char: "🏨"
    }, {
        name: "love_hotel",
        char: "🏩"
    }, {
        name: "convenience_store",
        char: "🏪"
    }, {
        name: "school",
        char: "🏫"
    }, {
        name: "department_store",
        char: "🏬"
    }, {
        name: "factory",
        char: "🏭"
    }, {
        name: "izakaya_lantern",
        char: "🏮"
    }, {
        name: "lantern",
        char: "🏮"
    }, {
        name: "japanese_castle",
        char: "🏯"
    }, {
        name: "european_castle",
        char: "🏰"
    }, {
        name: "rainbow-flag",
        char: "🏳️‍🌈"
    }, {
        name: "waving_white_flag",
        char: "🏳️"
    }, {
        name: "flag-england",
        char: "🏴󠁧󠁢󠁥󠁮󠁧󠁿"
    }, {
        name: "flag-scotland",
        char: "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
    }, {
        name: "flag-wales",
        char: "🏴󠁧󠁢󠁷󠁬󠁳󠁿"
    }, {
        name: "waving_black_flag",
        char: "🏴"
    }, {
        name: "rosette",
        char: "🏵️"
    }, {
        name: "label",
        char: "🏷️"
    }, {
        name: "badminton_racquet_and_shuttlecock",
        char: "🏸"
    }, {
        name: "bow_and_arrow",
        char: "🏹"
    }, {
        name: "amphora",
        char: "🏺"
    }, {
        name: "skin-tone-2",
        char: "🏻"
    }, {
        name: "skin-tone-3",
        char: "🏼"
    }, {
        name: "skin-tone-4",
        char: "🏽"
    }, {
        name: "skin-tone-5",
        char: "🏾"
    }, {
        name: "skin-tone-6",
        char: "🏿"
    }, {
        name: "rat",
        char: "🐀"
    }, {
        name: "mouse2",
        char: "🐁"
    }, {
        name: "ox",
        char: "🐂"
    }, {
        name: "water_buffalo",
        char: "🐃"
    }, {
        name: "cow2",
        char: "🐄"
    }, {
        name: "tiger2",
        char: "🐅"
    }, {
        name: "leopard",
        char: "🐆"
    }, {
        name: "rabbit2",
        char: "🐇"
    }, {
        name: "cat2",
        char: "🐈"
    }, {
        name: "dragon",
        char: "🐉"
    }, {
        name: "crocodile",
        char: "🐊"
    }, {
        name: "whale2",
        char: "🐋"
    }, {
        name: "snail",
        char: "🐌"
    }, {
        name: "snake",
        char: "🐍"
    }, {
        name: "racehorse",
        char: "🐎"
    }, {
        name: "ram",
        char: "🐏"
    }, {
        name: "goat",
        char: "🐐"
    }, {
        name: "sheep",
        char: "🐑"
    }, {
        name: "monkey",
        char: "🐒"
    }, {
        name: "rooster",
        char: "🐓"
    }, {
        name: "chicken",
        char: "🐔"
    }, {
        name: "dog2",
        char: "🐕"
    }, {
        name: "pig2",
        char: "🐖"
    }, {
        name: "boar",
        char: "🐗"
    }, {
        name: "elephant",
        char: "🐘"
    }, {
        name: "octopus",
        char: "🐙"
    }, {
        name: "shell",
        char: "🐚"
    }, {
        name: "bug",
        char: "🐛"
    }, {
        name: "ant",
        char: "🐜"
    }, {
        name: "bee",
        char: "🐝"
    }, {
        name: "honeybee",
        char: "🐝"
    }, {
        name: "beetle",
        char: "🐞"
    }, {
        name: "fish",
        char: "🐟"
    }, {
        name: "tropical_fish",
        char: "🐠"
    }, {
        name: "blowfish",
        char: "🐡"
    }, {
        name: "turtle",
        char: "🐢"
    }, {
        name: "hatching_chick",
        char: "🐣"
    }, {
        name: "baby_chick",
        char: "🐤"
    }, {
        name: "hatched_chick",
        char: "🐥"
    }, {
        name: "bird",
        char: "🐦"
    }, {
        name: "penguin",
        char: "🐧"
    }, {
        name: "koala",
        char: "🐨"
    }, {
        name: "poodle",
        char: "🐩"
    }, {
        name: "dromedary_camel",
        char: "🐪"
    }, {
        name: "camel",
        char: "🐫"
    }, {
        name: "dolphin",
        char: "🐬"
    }, {
        name: "flipper",
        char: "🐬"
    }, {
        name: "mouse",
        char: "🐭"
    }, {
        name: "cow",
        char: "🐮"
    }, {
        name: "tiger",
        char: "🐯"
    }, {
        name: "rabbit",
        char: "🐰"
    }, {
        name: "cat",
        char: "🐱"
    }, {
        name: "dragon_face",
        char: "🐲"
    }, {
        name: "whale",
        char: "🐳"
    }, {
        name: "horse",
        char: "🐴"
    }, {
        name: "monkey_face",
        char: "🐵"
    }, {
        name: "dog",
        char: "🐶"
    }, {
        name: "pig",
        char: "🐷"
    }, {
        name: "frog",
        char: "🐸"
    }, {
        name: "hamster",
        char: "🐹"
    }, {
        name: "wolf",
        char: "🐺"
    }, {
        name: "bear",
        char: "🐻"
    }, {
        name: "panda_face",
        char: "🐼"
    }, {
        name: "pig_nose",
        char: "🐽"
    }, {
        name: "feet",
        char: "🐾"
    }, {
        name: "paw_prints",
        char: "🐾"
    }, {
        name: "chipmunk",
        char: "🐿️"
    }, {
        name: "eyes",
        char: "👀"
    }, {
        name: "eye-in-speech-bubble",
        char: "👁️‍🗨️"
    }, {
        name: "eye",
        char: "👁️"
    }, {
        name: "ear",
        char: "👂"
    }, {
        name: "nose",
        char: "👃"
    }, {
        name: "lips",
        char: "👄"
    }, {
        name: "tongue",
        char: "👅"
    }, {
        name: "point_up_2",
        char: "👆"
    }, {
        name: "point_down",
        char: "👇"
    }, {
        name: "point_left",
        char: "👈"
    }, {
        name: "point_right",
        char: "👉"
    }, {
        name: "facepunch",
        char: "👊"
    }, {
        name: "punch",
        char: "👊"
    }, {
        name: "wave",
        char: "👋"
    }, {
        name: "ok_hand",
        char: "👌"
    }, {
        name: "+1",
        char: "👍"
    }, {
        name: "thumbsup",
        char: "👍"
    }, {
        name: "-1",
        char: "👎"
    }, {
        name: "thumbsdown",
        char: "👎"
    }, {
        name: "clap",
        char: "👏"
    }, {
        name: "open_hands",
        char: "👐"
    }, {
        name: "crown",
        char: "👑"
    }, {
        name: "womans_hat",
        char: "👒"
    }, {
        name: "eyeglasses",
        char: "👓"
    }, {
        name: "necktie",
        char: "👔"
    }, {
        name: "shirt",
        char: "👕"
    }, {
        name: "tshirt",
        char: "👕"
    }, {
        name: "jeans",
        char: "👖"
    }, {
        name: "dress",
        char: "👗"
    }, {
        name: "kimono",
        char: "👘"
    }, {
        name: "bikini",
        char: "👙"
    }, {
        name: "womans_clothes",
        char: "👚"
    }, {
        name: "purse",
        char: "👛"
    }, {
        name: "handbag",
        char: "👜"
    }, {
        name: "pouch",
        char: "👝"
    }, {
        name: "mans_shoe",
        char: "👞"
    }, {
        name: "shoe",
        char: "👞"
    }, {
        name: "athletic_shoe",
        char: "👟"
    }, {
        name: "high_heel",
        char: "👠"
    }, {
        name: "sandal",
        char: "👡"
    }, {
        name: "boot",
        char: "👢"
    }, {
        name: "footprints",
        char: "👣"
    }, {
        name: "bust_in_silhouette",
        char: "👤"
    }, {
        name: "busts_in_silhouette",
        char: "👥"
    }, {
        name: "boy",
        char: "👦"
    }, {
        name: "girl",
        char: "👧"
    }, {
        name: "male-farmer",
        char: "👨‍🌾"
    }, {
        name: "male-cook",
        char: "👨‍🍳"
    }, {
        name: "male-student",
        char: "👨‍🎓"
    }, {
        name: "male-singer",
        char: "👨‍🎤"
    }, {
        name: "male-artist",
        char: "👨‍🎨"
    }, {
        name: "male-teacher",
        char: "👨‍🏫"
    }, {
        name: "male-factory-worker",
        char: "👨‍🏭"
    }, {
        name: "man-boy-boy",
        char: "👨‍👦‍👦"
    }, {
        name: "man-boy",
        char: "👨‍👦"
    }, {
        name: "man-girl-boy",
        char: "👨‍👧‍👦"
    }, {
        name: "man-girl-girl",
        char: "👨‍👧‍👧"
    }, {
        name: "man-girl",
        char: "👨‍👧"
    }, {
        name: "man-man-boy",
        char: "👨‍👨‍👦"
    }, {
        name: "man-man-boy-boy",
        char: "👨‍👨‍👦‍👦"
    }, {
        name: "man-man-girl",
        char: "👨‍👨‍👧"
    }, {
        name: "man-man-girl-boy",
        char: "👨‍👨‍👧‍👦"
    }, {
        name: "man-man-girl-girl",
        char: "👨‍👨‍👧‍👧"
    }, {
        name: "man-woman-boy",
        char: "👨‍👩‍👦"
    }, {
        name: "family",
        char: "👨‍👩‍👦"
    }, {
        name: "man-woman-boy-boy",
        char: "👨‍👩‍👦‍👦"
    }, {
        name: "man-woman-girl",
        char: "👨‍👩‍👧"
    }, {
        name: "man-woman-girl-boy",
        char: "👨‍👩‍👧‍👦"
    }, {
        name: "man-woman-girl-girl",
        char: "👨‍👩‍👧‍👧"
    }, {
        name: "male-technologist",
        char: "👨‍💻"
    }, {
        name: "male-office-worker",
        char: "👨‍💼"
    }, {
        name: "male-mechanic",
        char: "👨‍🔧"
    }, {
        name: "male-scientist",
        char: "👨‍🔬"
    }, {
        name: "male-astronaut",
        char: "👨‍🚀"
    }, {
        name: "male-firefighter",
        char: "👨‍🚒"
    }, {
        name: "male-doctor",
        char: "👨‍⚕️"
    }, {
        name: "male-judge",
        char: "👨‍⚖️"
    }, {
        name: "male-pilot",
        char: "👨‍✈️"
    }, {
        name: "man-heart-man",
        char: "👨‍❤️‍👨"
    }, {
        name: "man-kiss-man",
        char: "👨‍❤️‍💋‍👨"
    }, {
        name: "man",
        char: "👨"
    }, {
        name: "female-farmer",
        char: "👩‍🌾"
    }, {
        name: "female-cook",
        char: "👩‍🍳"
    }, {
        name: "female-student",
        char: "👩‍🎓"
    }, {
        name: "female-singer",
        char: "👩‍🎤"
    }, {
        name: "female-artist",
        char: "👩‍🎨"
    }, {
        name: "female-teacher",
        char: "👩‍🏫"
    }, {
        name: "female-factory-worker",
        char: "👩‍🏭"
    }, {
        name: "woman-boy-boy",
        char: "👩‍👦‍👦"
    }, {
        name: "woman-boy",
        char: "👩‍👦"
    }, {
        name: "woman-girl-boy",
        char: "👩‍👧‍👦"
    }, {
        name: "woman-girl-girl",
        char: "👩‍👧‍👧"
    }, {
        name: "woman-girl",
        char: "👩‍👧"
    }, {
        name: "woman-woman-boy",
        char: "👩‍👩‍👦"
    }, {
        name: "woman-woman-boy-boy",
        char: "👩‍👩‍👦‍👦"
    }, {
        name: "woman-woman-girl",
        char: "👩‍👩‍👧"
    }, {
        name: "woman-woman-girl-boy",
        char: "👩‍👩‍👧‍👦"
    }, {
        name: "woman-woman-girl-girl",
        char: "👩‍👩‍👧‍👧"
    }, {
        name: "female-technologist",
        char: "👩‍💻"
    }, {
        name: "female-office-worker",
        char: "👩‍💼"
    }, {
        name: "female-mechanic",
        char: "👩‍🔧"
    }, {
        name: "female-scientist",
        char: "👩‍🔬"
    }, {
        name: "female-astronaut",
        char: "👩‍🚀"
    }, {
        name: "female-firefighter",
        char: "👩‍🚒"
    }, {
        name: "female-doctor",
        char: "👩‍⚕️"
    }, {
        name: "female-judge",
        char: "👩‍⚖️"
    }, {
        name: "female-pilot",
        char: "👩‍✈️"
    }, {
        name: "woman-heart-man",
        char: "👩‍❤️‍👨"
    }, {
        name: "couple_with_heart",
        char: "👩‍❤️‍👨"
    }, {
        name: "woman-heart-woman",
        char: "👩‍❤️‍👩"
    }, {
        name: "woman-kiss-man",
        char: "👩‍❤️‍💋‍👨"
    }, {
        name: "couplekiss",
        char: "👩‍❤️‍💋‍👨"
    }, {
        name: "woman-kiss-woman",
        char: "👩‍❤️‍💋‍👩"
    }, {
        name: "woman",
        char: "👩"
    }, {
        name: "couple",
        char: "👫"
    }, {
        name: "man_and_woman_holding_hands",
        char: "👫"
    }, {
        name: "two_men_holding_hands",
        char: "👬"
    }, {
        name: "two_women_holding_hands",
        char: "👭"
    }, {
        name: "female-police-officer",
        char: "👮‍♀️"
    }, {
        name: "male-police-officer",
        char: "👮‍♂️"
    }, {
        name: "cop",
        char: "👮‍♂️"
    }, {
        name: "woman-with-bunny-ears-partying",
        char: "👯‍♀️"
    }, {
        name: "dancers",
        char: "👯‍♀️"
    }, {
        name: "man-with-bunny-ears-partying",
        char: "👯‍♂️"
    }, {
        name: "bride_with_veil",
        char: "👰"
    }, {
        name: "blond-haired-woman",
        char: "👱‍♀️"
    }, {
        name: "blond-haired-man",
        char: "👱‍♂️"
    }, {
        name: "person_with_blond_hair",
        char: "👱‍♂️"
    }, {
        name: "man_with_gua_pi_mao",
        char: "👲"
    }, {
        name: "woman-wearing-turban",
        char: "👳‍♀️"
    }, {
        name: "man-wearing-turban",
        char: "👳‍♂️"
    }, {
        name: "man_with_turban",
        char: "👳‍♂️"
    }, {
        name: "older_man",
        char: "👴"
    }, {
        name: "older_woman",
        char: "👵"
    }, {
        name: "baby",
        char: "👶"
    }, {
        name: "female-construction-worker",
        char: "👷‍♀️"
    }, {
        name: "male-construction-worker",
        char: "👷‍♂️"
    }, {
        name: "construction_worker",
        char: "👷‍♂️"
    }, {
        name: "princess",
        char: "👸"
    }, {
        name: "japanese_ogre",
        char: "👹"
    }, {
        name: "japanese_goblin",
        char: "👺"
    }, {
        name: "ghost",
        char: "👻"
    }, {
        name: "angel",
        char: "👼"
    }, {
        name: "alien",
        char: "👽"
    }, {
        name: "space_invader",
        char: "👾"
    }, {
        name: "imp",
        char: "👿"
    }, {
        name: "skull",
        char: "💀"
    }, {
        name: "woman-tipping-hand",
        char: "💁‍♀️"
    }, {
        name: "information_desk_person",
        char: "💁‍♀️"
    }, {
        name: "man-tipping-hand",
        char: "💁‍♂️"
    }, {
        name: "female-guard",
        char: "💂‍♀️"
    }, {
        name: "male-guard",
        char: "💂‍♂️"
    }, {
        name: "guardsman",
        char: "💂‍♂️"
    }, {
        name: "dancer",
        char: "💃"
    }, {
        name: "lipstick",
        char: "💄"
    }, {
        name: "nail_care",
        char: "💅"
    }, {
        name: "woman-getting-massage",
        char: "💆‍♀️"
    }, {
        name: "massage",
        char: "💆‍♀️"
    }, {
        name: "man-getting-massage",
        char: "💆‍♂️"
    }, {
        name: "woman-getting-haircut",
        char: "💇‍♀️"
    }, {
        name: "haircut",
        char: "💇‍♀️"
    }, {
        name: "man-getting-haircut",
        char: "💇‍♂️"
    }, {
        name: "barber",
        char: "💈"
    }, {
        name: "syringe",
        char: "💉"
    }, {
        name: "pill",
        char: "💊"
    }, {
        name: "kiss",
        char: "💋"
    }, {
        name: "love_letter",
        char: "💌"
    }, {
        name: "ring",
        char: "💍"
    }, {
        name: "gem",
        char: "💎"
    }, {
        name: "bouquet",
        char: "💐"
    }, {
        name: "wedding",
        char: "💒"
    }, {
        name: "heartbeat",
        char: "💓"
    }, {
        name: "broken_heart",
        char: "💔"
    }, {
        name: "two_hearts",
        char: "💕"
    }, {
        name: "sparkling_heart",
        char: "💖"
    }, {
        name: "heartpulse",
        char: "💗"
    }, {
        name: "cupid",
        char: "💘"
    }, {
        name: "blue_heart",
        char: "💙"
    }, {
        name: "green_heart",
        char: "💚"
    }, {
        name: "yellow_heart",
        char: "💛"
    }, {
        name: "purple_heart",
        char: "💜"
    }, {
        name: "gift_heart",
        char: "💝"
    }, {
        name: "revolving_hearts",
        char: "💞"
    }, {
        name: "heart_decoration",
        char: "💟"
    }, {
        name: "diamond_shape_with_a_dot_inside",
        char: "💠"
    }, {
        name: "bulb",
        char: "💡"
    }, {
        name: "anger",
        char: "💢"
    }, {
        name: "bomb",
        char: "💣"
    }, {
        name: "zzz",
        char: "💤"
    }, {
        name: "boom",
        char: "💥"
    }, {
        name: "collision",
        char: "💥"
    }, {
        name: "sweat_drops",
        char: "💦"
    }, {
        name: "droplet",
        char: "💧"
    }, {
        name: "dash",
        char: "💨"
    }, {
        name: "hankey",
        char: "💩"
    }, {
        name: "poop",
        char: "💩"
    }, {
        name: "shit",
        char: "💩"
    }, {
        name: "muscle",
        char: "💪"
    }, {
        name: "dizzy",
        char: "💫"
    }, {
        name: "speech_balloon",
        char: "💬"
    }, {
        name: "thought_balloon",
        char: "💭"
    }, {
        name: "white_flower",
        char: "💮"
    }, {
        name: "moneybag",
        char: "💰"
    }, {
        name: "currency_exchange",
        char: "💱"
    }, {
        name: "heavy_dollar_sign",
        char: "💲"
    }, {
        name: "credit_card",
        char: "💳"
    }, {
        name: "yen",
        char: "💴"
    }, {
        name: "dollar",
        char: "💵"
    }, {
        name: "euro",
        char: "💶"
    }, {
        name: "pound",
        char: "💷"
    }, {
        name: "money_with_wings",
        char: "💸"
    }, {
        name: "chart",
        char: "💹"
    }, {
        name: "seat",
        char: "💺"
    }, {
        name: "computer",
        char: "💻"
    }, {
        name: "briefcase",
        char: "💼"
    }, {
        name: "minidisc",
        char: "💽"
    }, {
        name: "floppy_disk",
        char: "💾"
    }, {
        name: "cd",
        char: "💿"
    }, {
        name: "dvd",
        char: "📀"
    }, {
        name: "file_folder",
        char: "📁"
    }, {
        name: "open_file_folder",
        char: "📂"
    }, {
        name: "page_with_curl",
        char: "📃"
    }, {
        name: "page_facing_up",
        char: "📄"
    }, {
        name: "date",
        char: "📅"
    }, {
        name: "calendar",
        char: "📆"
    }, {
        name: "card_index",
        char: "📇"
    }, {
        name: "chart_with_upwards_trend",
        char: "📈"
    }, {
        name: "chart_with_downwards_trend",
        char: "📉"
    }, {
        name: "bar_chart",
        char: "📊"
    }, {
        name: "clipboard",
        char: "📋"
    }, {
        name: "pushpin",
        char: "📌"
    }, {
        name: "round_pushpin",
        char: "📍"
    }, {
        name: "paperclip",
        char: "📎"
    }, {
        name: "straight_ruler",
        char: "📏"
    }, {
        name: "triangular_ruler",
        char: "📐"
    }, {
        name: "bookmark_tabs",
        char: "📑"
    }, {
        name: "ledger",
        char: "📒"
    }, {
        name: "notebook",
        char: "📓"
    }, {
        name: "notebook_with_decorative_cover",
        char: "📔"
    }, {
        name: "closed_book",
        char: "📕"
    }, {
        name: "book",
        char: "📖"
    }, {
        name: "open_book",
        char: "📖"
    }, {
        name: "green_book",
        char: "📗"
    }, {
        name: "blue_book",
        char: "📘"
    }, {
        name: "orange_book",
        char: "📙"
    }, {
        name: "books",
        char: "📚"
    }, {
        name: "name_badge",
        char: "📛"
    }, {
        name: "scroll",
        char: "📜"
    }, {
        name: "memo",
        char: "📝"
    }, {
        name: "pencil",
        char: "📝"
    }, {
        name: "telephone_receiver",
        char: "📞"
    }, {
        name: "pager",
        char: "📟"
    }, {
        name: "fax",
        char: "📠"
    }, {
        name: "satellite_antenna",
        char: "📡"
    }, {
        name: "loudspeaker",
        char: "📢"
    }, {
        name: "mega",
        char: "📣"
    }, {
        name: "outbox_tray",
        char: "📤"
    }, {
        name: "inbox_tray",
        char: "📥"
    }, {
        name: "package",
        char: "📦"
    }, {
        name: "e-mail",
        char: "📧"
    }, {
        name: "email",
        char: "📧"
    }, {
        name: "incoming_envelope",
        char: "📨"
    }, {
        name: "envelope_with_arrow",
        char: "📩"
    }, {
        name: "mailbox_closed",
        char: "📪"
    }, {
        name: "mailbox",
        char: "📫"
    }, {
        name: "mailbox_with_mail",
        char: "📬"
    }, {
        name: "mailbox_with_no_mail",
        char: "📭"
    }, {
        name: "postbox",
        char: "📮"
    }, {
        name: "postal_horn",
        char: "📯"
    }, {
        name: "newspaper",
        char: "📰"
    }, {
        name: "iphone",
        char: "📱"
    }, {
        name: "calling",
        char: "📲"
    }, {
        name: "vibration_mode",
        char: "📳"
    }, {
        name: "mobile_phone_off",
        char: "📴"
    }, {
        name: "no_mobile_phones",
        char: "📵"
    }, {
        name: "signal_strength",
        char: "📶"
    }, {
        name: "camera",
        char: "📷"
    }, {
        name: "camera_with_flash",
        char: "📸"
    }, {
        name: "video_camera",
        char: "📹"
    }, {
        name: "tv",
        char: "📺"
    }, {
        name: "radio",
        char: "📻"
    }, {
        name: "vhs",
        char: "📼"
    }, {
        name: "film_projector",
        char: "📽️"
    }, {
        name: "prayer_beads",
        char: "📿"
    }, {
        name: "twisted_rightwards_arrows",
        char: "🔀"
    }, {
        name: "repeat",
        char: "🔁"
    }, {
        name: "repeat_one",
        char: "🔂"
    }, {
        name: "arrows_clockwise",
        char: "🔃"
    }, {
        name: "arrows_counterclockwise",
        char: "🔄"
    }, {
        name: "low_brightness",
        char: "🔅"
    }, {
        name: "high_brightness",
        char: "🔆"
    }, {
        name: "mute",
        char: "🔇"
    }, {
        name: "speaker",
        char: "🔈"
    }, {
        name: "sound",
        char: "🔉"
    }, {
        name: "loud_sound",
        char: "🔊"
    }, {
        name: "battery",
        char: "🔋"
    }, {
        name: "electric_plug",
        char: "🔌"
    }, {
        name: "mag",
        char: "🔍"
    }, {
        name: "mag_right",
        char: "🔎"
    }, {
        name: "lock_with_ink_pen",
        char: "🔏"
    }, {
        name: "closed_lock_with_key",
        char: "🔐"
    }, {
        name: "key",
        char: "🔑"
    }, {
        name: "lock",
        char: "🔒"
    }, {
        name: "unlock",
        char: "🔓"
    }, {
        name: "bell",
        char: "🔔"
    }, {
        name: "no_bell",
        char: "🔕"
    }, {
        name: "bookmark",
        char: "🔖"
    }, {
        name: "link",
        char: "🔗"
    }, {
        name: "radio_button",
        char: "🔘"
    }, {
        name: "back",
        char: "🔙"
    }, {
        name: "end",
        char: "🔚"
    }, {
        name: "on",
        char: "🔛"
    }, {
        name: "soon",
        char: "🔜"
    }, {
        name: "top",
        char: "🔝"
    }, {
        name: "underage",
        char: "🔞"
    }, {
        name: "keycap_ten",
        char: "🔟"
    }, {
        name: "capital_abcd",
        char: "🔠"
    }, {
        name: "abcd",
        char: "🔡"
    }, {
        name: "symbols",
        char: "🔣"
    }, {
        name: "abc",
        char: "🔤"
    }, {
        name: "fire",
        char: "🔥"
    }, {
        name: "flashlight",
        char: "🔦"
    }, {
        name: "wrench",
        char: "🔧"
    }, {
        name: "hammer",
        char: "🔨"
    }, {
        name: "nut_and_bolt",
        char: "🔩"
    }, {
        name: "hocho",
        char: "🔪"
    }, {
        name: "knife",
        char: "🔪"
    }, {
        name: "gun",
        char: "🔫"
    }, {
        name: "microscope",
        char: "🔬"
    }, {
        name: "telescope",
        char: "🔭"
    }, {
        name: "crystal_ball",
        char: "🔮"
    }, {
        name: "six_pointed_star",
        char: "🔯"
    }, {
        name: "beginner",
        char: "🔰"
    }, {
        name: "trident",
        char: "🔱"
    }, {
        name: "black_square_button",
        char: "🔲"
    }, {
        name: "white_square_button",
        char: "🔳"
    }, {
        name: "red_circle",
        char: "🔴"
    }, {
        name: "large_blue_circle",
        char: "🔵"
    }, {
        name: "large_orange_diamond",
        char: "🔶"
    }, {
        name: "large_blue_diamond",
        char: "🔷"
    }, {
        name: "small_orange_diamond",
        char: "🔸"
    }, {
        name: "small_blue_diamond",
        char: "🔹"
    }, {
        name: "small_red_triangle",
        char: "🔺"
    }, {
        name: "small_red_triangle_down",
        char: "🔻"
    }, {
        name: "arrow_up_small",
        char: "🔼"
    }, {
        name: "arrow_down_small",
        char: "🔽"
    }, {
        name: "om_symbol",
        char: "🕉️"
    }, {
        name: "dove_of_peace",
        char: "🕊️"
    }, {
        name: "kaaba",
        char: "🕋"
    }, {
        name: "mosque",
        char: "🕌"
    }, {
        name: "synagogue",
        char: "🕍"
    }, {
        name: "menorah_with_nine_branches",
        char: "🕎"
    }, {
        name: "clock1",
        char: "🕐"
    }, {
        name: "clock2",
        char: "🕑"
    }, {
        name: "clock3",
        char: "🕒"
    }, {
        name: "clock4",
        char: "🕓"
    }, {
        name: "clock5",
        char: "🕔"
    }, {
        name: "clock6",
        char: "🕕"
    }, {
        name: "clock7",
        char: "🕖"
    }, {
        name: "clock8",
        char: "🕗"
    }, {
        name: "clock9",
        char: "🕘"
    }, {
        name: "clock10",
        char: "🕙"
    }, {
        name: "clock11",
        char: "🕚"
    }, {
        name: "clock12",
        char: "🕛"
    }, {
        name: "clock130",
        char: "🕜"
    }, {
        name: "clock230",
        char: "🕝"
    }, {
        name: "clock330",
        char: "🕞"
    }, {
        name: "clock430",
        char: "🕟"
    }, {
        name: "clock530",
        char: "🕠"
    }, {
        name: "clock630",
        char: "🕡"
    }, {
        name: "clock730",
        char: "🕢"
    }, {
        name: "clock830",
        char: "🕣"
    }, {
        name: "clock930",
        char: "🕤"
    }, {
        name: "clock1030",
        char: "🕥"
    }, {
        name: "clock1130",
        char: "🕦"
    }, {
        name: "clock1230",
        char: "🕧"
    }, {
        name: "candle",
        char: "🕯️"
    }, {
        name: "mantelpiece_clock",
        char: "🕰️"
    }, {
        name: "hole",
        char: "🕳️"
    }, {
        name: "man_in_business_suit_levitating",
        char: "🕴️"
    }, {
        name: "female-detective",
        char: "🕵️‍♀️"
    }, {
        name: "male-detective",
        char: "🕵️‍♂️"
    }, {
        name: "sleuth_or_spy",
        char: "🕵️‍♂️"
    }, {
        name: "dark_sunglasses",
        char: "🕶️"
    }, {
        name: "spider",
        char: "🕷️"
    }, {
        name: "spider_web",
        char: "🕸️"
    }, {
        name: "joystick",
        char: "🕹️"
    }, {
        name: "man_dancing",
        char: "🕺"
    }, {
        name: "linked_paperclips",
        char: "🖇️"
    }, {
        name: "lower_left_ballpoint_pen",
        char: "🖊️"
    }, {
        name: "lower_left_fountain_pen",
        char: "🖋️"
    }, {
        name: "lower_left_paintbrush",
        char: "🖌️"
    }, {
        name: "lower_left_crayon",
        char: "🖍️"
    }, {
        name: "raised_hand_with_fingers_splayed",
        char: "🖐️"
    }, {
        name: "middle_finger",
        char: "🖕"
    }, {
        name: "reversed_hand_with_middle_finger_extended",
        char: "🖕"
    }, {
        name: "spock-hand",
        char: "🖖"
    }, {
        name: "black_heart",
        char: "🖤"
    }, {
        name: "desktop_computer",
        char: "🖥️"
    }, {
        name: "printer",
        char: "🖨️"
    }, {
        name: "three_button_mouse",
        char: "🖱️"
    }, {
        name: "trackball",
        char: "🖲️"
    }, {
        name: "frame_with_picture",
        char: "🖼️"
    }, {
        name: "card_index_dividers",
        char: "🗂️"
    }, {
        name: "card_file_box",
        char: "🗃️"
    }, {
        name: "file_cabinet",
        char: "🗄️"
    }, {
        name: "wastebasket",
        char: "🗑️"
    }, {
        name: "spiral_note_pad",
        char: "🗒️"
    }, {
        name: "spiral_calendar_pad",
        char: "🗓️"
    }, {
        name: "compression",
        char: "🗜️"
    }, {
        name: "old_key",
        char: "🗝️"
    }, {
        name: "rolled_up_newspaper",
        char: "🗞️"
    }, {
        name: "dagger_knife",
        char: "🗡️"
    }, {
        name: "speaking_head_in_silhouette",
        char: "🗣️"
    }, {
        name: "left_speech_bubble",
        char: "🗨️"
    }, {
        name: "right_anger_bubble",
        char: "🗯️"
    }, {
        name: "ballot_box_with_ballot",
        char: "🗳️"
    }, {
        name: "world_map",
        char: "🗺️"
    }, {
        name: "mount_fuji",
        char: "🗻"
    }, {
        name: "tokyo_tower",
        char: "🗼"
    }, {
        name: "statue_of_liberty",
        char: "🗽"
    }, {
        name: "japan",
        char: "🗾"
    }, {
        name: "moyai",
        char: "🗿"
    }, {
        name: "grinning",
        char: "😀"
    }, {
        name: "grin",
        char: "😁"
    }, {
        name: "joy",
        char: "😂"
    }, {
        name: "smiley",
        char: "😃"
    }, {
        name: "smile",
        char: "😄"
    }, {
        name: "sweat_smile",
        char: "😅"
    }, {
        name: "laughing",
        char: "😆"
    }, {
        name: "satisfied",
        char: "😆"
    }, {
        name: "innocent",
        char: "😇"
    }, {
        name: "smiling_imp",
        char: "😈"
    }, {
        name: "wink",
        char: "😉"
    }, {
        name: "blush",
        char: "😊"
    }, {
        name: "yum",
        char: "😋"
    }, {
        name: "relieved",
        char: "😌"
    }, {
        name: "heart_eyes",
        char: "😍"
    }, {
        name: "sunglasses",
        char: "😎"
    }, {
        name: "smirk",
        char: "😏"
    }, {
        name: "neutral_face",
        char: "😐"
    }, {
        name: "expressionless",
        char: "😑"
    }, {
        name: "unamused",
        char: "😒"
    }, {
        name: "sweat",
        char: "😓"
    }, {
        name: "pensive",
        char: "😔"
    }, {
        name: "confused",
        char: "😕"
    }, {
        name: "confounded",
        char: "😖"
    }, {
        name: "kissing",
        char: "😗"
    }, {
        name: "kissing_heart",
        char: "😘"
    }, {
        name: "kissing_smiling_eyes",
        char: "😙"
    }, {
        name: "kissing_closed_eyes",
        char: "😚"
    }, {
        name: "stuck_out_tongue",
        char: "😛"
    }, {
        name: "stuck_out_tongue_winking_eye",
        char: "😜"
    }, {
        name: "stuck_out_tongue_closed_eyes",
        char: "😝"
    }, {
        name: "disappointed",
        char: "😞"
    }, {
        name: "worried",
        char: "😟"
    }, {
        name: "angry",
        char: "😠"
    }, {
        name: "rage",
        char: "😡"
    }, {
        name: "cry",
        char: "😢"
    }, {
        name: "persevere",
        char: "😣"
    }, {
        name: "triumph",
        char: "😤"
    }, {
        name: "disappointed_relieved",
        char: "😥"
    }, {
        name: "frowning",
        char: "😦"
    }, {
        name: "anguished",
        char: "😧"
    }, {
        name: "fearful",
        char: "😨"
    }, {
        name: "weary",
        char: "😩"
    }, {
        name: "sleepy",
        char: "😪"
    }, {
        name: "tired_face",
        char: "😫"
    }, {
        name: "grimacing",
        char: "😬"
    }, {
        name: "sob",
        char: "😭"
    }, {
        name: "open_mouth",
        char: "😮"
    }, {
        name: "hushed",
        char: "😯"
    }, {
        name: "cold_sweat",
        char: "😰"
    }, {
        name: "scream",
        char: "😱"
    }, {
        name: "astonished",
        char: "😲"
    }, {
        name: "flushed",
        char: "😳"
    }, {
        name: "sleeping",
        char: "😴"
    }, {
        name: "dizzy_face",
        char: "😵"
    }, {
        name: "no_mouth",
        char: "😶"
    }, {
        name: "mask",
        char: "😷"
    }, {
        name: "smile_cat",
        char: "😸"
    }, {
        name: "joy_cat",
        char: "😹"
    }, {
        name: "smiley_cat",
        char: "😺"
    }, {
        name: "heart_eyes_cat",
        char: "😻"
    }, {
        name: "smirk_cat",
        char: "😼"
    }, {
        name: "kissing_cat",
        char: "😽"
    }, {
        name: "pouting_cat",
        char: "😾"
    }, {
        name: "crying_cat_face",
        char: "😿"
    }, {
        name: "scream_cat",
        char: "🙀"
    }, {
        name: "slightly_frowning_face",
        char: "🙁"
    }, {
        name: "slightly_smiling_face",
        char: "🙂"
    }, {
        name: "upside_down_face",
        char: "🙃"
    }, {
        name: "face_with_rolling_eyes",
        char: "🙄"
    }, {
        name: "woman-gesturing-no",
        char: "🙅‍♀️"
    }, {
        name: "no_good",
        char: "🙅‍♀️"
    }, {
        name: "man-gesturing-no",
        char: "🙅‍♂️"
    }, {
        name: "woman-gesturing-ok",
        char: "🙆‍♀️"
    }, {
        name: "ok_woman",
        char: "🙆‍♀️"
    }, {
        name: "man-gesturing-ok",
        char: "🙆‍♂️"
    }, {
        name: "woman-bowing",
        char: "🙇‍♀️"
    }, {
        name: "man-bowing",
        char: "🙇‍♂️"
    }, {
        name: "bow",
        char: "🙇‍♂️"
    }, {
        name: "see_no_evil",
        char: "🙈"
    }, {
        name: "hear_no_evil",
        char: "🙉"
    }, {
        name: "speak_no_evil",
        char: "🙊"
    }, {
        name: "woman-raising-hand",
        char: "🙋‍♀️"
    }, {
        name: "raising_hand",
        char: "🙋‍♀️"
    }, {
        name: "man-raising-hand",
        char: "🙋‍♂️"
    }, {
        name: "raised_hands",
        char: "🙌"
    }, {
        name: "woman-frowning",
        char: "🙍‍♀️"
    }, {
        name: "person_frowning",
        char: "🙍‍♀️"
    }, {
        name: "man-frowning",
        char: "🙍‍♂️"
    }, {
        name: "woman-pouting",
        char: "🙎‍♀️"
    }, {
        name: "person_with_pouting_face",
        char: "🙎‍♀️"
    }, {
        name: "man-pouting",
        char: "🙎‍♂️"
    }, {
        name: "pray",
        char: "🙏"
    }, {
        name: "rocket",
        char: "🚀"
    }, {
        name: "helicopter",
        char: "🚁"
    }, {
        name: "steam_locomotive",
        char: "🚂"
    }, {
        name: "railway_car",
        char: "🚃"
    }, {
        name: "bullettrain_side",
        char: "🚄"
    }, {
        name: "bullettrain_front",
        char: "🚅"
    }, {
        name: "train2",
        char: "🚆"
    }, {
        name: "metro",
        char: "🚇"
    }, {
        name: "light_rail",
        char: "🚈"
    }, {
        name: "station",
        char: "🚉"
    }, {
        name: "tram",
        char: "🚊"
    }, {
        name: "train",
        char: "🚋"
    }, {
        name: "bus",
        char: "🚌"
    }, {
        name: "oncoming_bus",
        char: "🚍"
    }, {
        name: "trolleybus",
        char: "🚎"
    }, {
        name: "busstop",
        char: "🚏"
    }, {
        name: "minibus",
        char: "🚐"
    }, {
        name: "ambulance",
        char: "🚑"
    }, {
        name: "fire_engine",
        char: "🚒"
    }, {
        name: "police_car",
        char: "🚓"
    }, {
        name: "oncoming_police_car",
        char: "🚔"
    }, {
        name: "taxi",
        char: "🚕"
    }, {
        name: "oncoming_taxi",
        char: "🚖"
    }, {
        name: "car",
        char: "🚗"
    }, {
        name: "red_car",
        char: "🚗"
    }, {
        name: "oncoming_automobile",
        char: "🚘"
    }, {
        name: "blue_car",
        char: "🚙"
    }, {
        name: "truck",
        char: "🚚"
    }, {
        name: "articulated_lorry",
        char: "🚛"
    }, {
        name: "tractor",
        char: "🚜"
    }, {
        name: "monorail",
        char: "🚝"
    }, {
        name: "mountain_railway",
        char: "🚞"
    }, {
        name: "suspension_railway",
        char: "🚟"
    }, {
        name: "mountain_cableway",
        char: "🚠"
    }, {
        name: "aerial_tramway",
        char: "🚡"
    }, {
        name: "ship",
        char: "🚢"
    }, {
        name: "woman-rowing-boat",
        char: "🚣‍♀️"
    }, {
        name: "man-rowing-boat",
        char: "🚣‍♂️"
    }, {
        name: "rowboat",
        char: "🚣‍♂️"
    }, {
        name: "speedboat",
        char: "🚤"
    }, {
        name: "traffic_light",
        char: "🚥"
    }, {
        name: "vertical_traffic_light",
        char: "🚦"
    }, {
        name: "construction",
        char: "🚧"
    }, {
        name: "rotating_light",
        char: "🚨"
    }, {
        name: "triangular_flag_on_post",
        char: "🚩"
    }, {
        name: "door",
        char: "🚪"
    }, {
        name: "no_entry_sign",
        char: "🚫"
    }, {
        name: "smoking",
        char: "🚬"
    }, {
        name: "no_smoking",
        char: "🚭"
    }, {
        name: "put_litter_in_its_place",
        char: "🚮"
    }, {
        name: "do_not_litter",
        char: "🚯"
    }, {
        name: "potable_water",
        char: "🚰"
    }, {
        name: "non-potable_water",
        char: "🚱"
    }, {
        name: "bike",
        char: "🚲"
    }, {
        name: "no_bicycles",
        char: "🚳"
    }, {
        name: "woman-biking",
        char: "🚴‍♀️"
    }, {
        name: "man-biking",
        char: "🚴‍♂️"
    }, {
        name: "bicyclist",
        char: "🚴‍♂️"
    }, {
        name: "woman-mountain-biking",
        char: "🚵‍♀️"
    }, {
        name: "man-mountain-biking",
        char: "🚵‍♂️"
    }, {
        name: "mountain_bicyclist",
        char: "🚵‍♂️"
    }, {
        name: "woman-walking",
        char: "🚶‍♀️"
    }, {
        name: "man-walking",
        char: "🚶‍♂️"
    }, {
        name: "walking",
        char: "🚶‍♂️"
    }, {
        name: "no_pedestrians",
        char: "🚷"
    }, {
        name: "children_crossing",
        char: "🚸"
    }, {
        name: "mens",
        char: "🚹"
    }, {
        name: "womens",
        char: "🚺"
    }, {
        name: "restroom",
        char: "🚻"
    }, {
        name: "baby_symbol",
        char: "🚼"
    }, {
        name: "toilet",
        char: "🚽"
    }, {
        name: "wc",
        char: "🚾"
    }, {
        name: "shower",
        char: "🚿"
    }, {
        name: "bath",
        char: "🛀"
    }, {
        name: "bathtub",
        char: "🛁"
    }, {
        name: "passport_control",
        char: "🛂"
    }, {
        name: "customs",
        char: "🛃"
    }, {
        name: "baggage_claim",
        char: "🛄"
    }, {
        name: "left_luggage",
        char: "🛅"
    }, {
        name: "couch_and_lamp",
        char: "🛋️"
    }, {
        name: "sleeping_accommodation",
        char: "🛌"
    }, {
        name: "shopping_bags",
        char: "🛍️"
    }, {
        name: "bellhop_bell",
        char: "🛎️"
    }, {
        name: "bed",
        char: "🛏️"
    }, {
        name: "place_of_worship",
        char: "🛐"
    }, {
        name: "octagonal_sign",
        char: "🛑"
    }, {
        name: "shopping_trolley",
        char: "🛒"
    }, {
        name: "hammer_and_wrench",
        char: "🛠️"
    }, {
        name: "shield",
        char: "🛡️"
    }, {
        name: "oil_drum",
        char: "🛢️"
    }, {
        name: "motorway",
        char: "🛣️"
    }, {
        name: "railway_track",
        char: "🛤️"
    }, {
        name: "motor_boat",
        char: "🛥️"
    }, {
        name: "small_airplane",
        char: "🛩️"
    }, {
        name: "airplane_departure",
        char: "🛫"
    }, {
        name: "airplane_arriving",
        char: "🛬"
    }, {
        name: "satellite",
        char: "🛰️"
    }, {
        name: "passenger_ship",
        char: "🛳️"
    }, {
        name: "scooter",
        char: "🛴"
    }, {
        name: "motor_scooter",
        char: "🛵"
    }, {
        name: "canoe",
        char: "🛶"
    }, {
        name: "sled",
        char: "🛷"
    }, {
        name: "flying_saucer",
        char: "🛸"
    }, {
        name: "zipper_mouth_face",
        char: "🤐"
    }, {
        name: "money_mouth_face",
        char: "🤑"
    }, {
        name: "face_with_thermometer",
        char: "🤒"
    }, {
        name: "nerd_face",
        char: "🤓"
    }, {
        name: "thinking_face",
        char: "🤔"
    }, {
        name: "face_with_head_bandage",
        char: "🤕"
    }, {
        name: "robot_face",
        char: "🤖"
    }, {
        name: "hugging_face",
        char: "🤗"
    }, {
        name: "the_horns",
        char: "🤘"
    }, {
        name: "sign_of_the_horns",
        char: "🤘"
    }, {
        name: "call_me_hand",
        char: "🤙"
    }, {
        name: "raised_back_of_hand",
        char: "🤚"
    }, {
        name: "left-facing_fist",
        char: "🤛"
    }, {
        name: "right-facing_fist",
        char: "🤜"
    }, {
        name: "handshake",
        char: "🤝"
    }, {
        name: "crossed_fingers",
        char: "🤞"
    }, {
        name: "hand_with_index_and_middle_fingers_crossed",
        char: "🤞"
    }, {
        name: "i_love_you_hand_sign",
        char: "🤟"
    }, {
        name: "face_with_cowboy_hat",
        char: "🤠"
    }, {
        name: "clown_face",
        char: "🤡"
    }, {
        name: "nauseated_face",
        char: "🤢"
    }, {
        name: "rolling_on_the_floor_laughing",
        char: "🤣"
    }, {
        name: "drooling_face",
        char: "🤤"
    }, {
        name: "lying_face",
        char: "🤥"
    }, {
        name: "woman-facepalming",
        char: "🤦‍♀️"
    }, {
        name: "man-facepalming",
        char: "🤦‍♂️"
    }, {
        name: "face_palm",
        char: "🤦"
    }, {
        name: "sneezing_face",
        char: "🤧"
    }, {
        name: "face_with_raised_eyebrow",
        char: "🤨"
    }, {
        name: "face_with_one_eyebrow_raised",
        char: "🤨"
    }, {
        name: "star-struck",
        char: "🤩"
    }, {
        name: "grinning_face_with_star_eyes",
        char: "🤩"
    }, {
        name: "zany_face",
        char: "🤪"
    }, {
        name: "grinning_face_with_one_large_and_one_small_eye",
        char: "🤪"
    }, {
        name: "shushing_face",
        char: "🤫"
    }, {
        name: "face_with_finger_covering_closed_lips",
        char: "🤫"
    }, {
        name: "face_with_symbols_on_mouth",
        char: "🤬"
    }, {
        name: "serious_face_with_symbols_covering_mouth",
        char: "🤬"
    }, {
        name: "face_with_hand_over_mouth",
        char: "🤭"
    }, {
        name: "smiling_face_with_smiling_eyes_and_hand_covering_mouth",
        char: "🤭"
    }, {
        name: "face_vomiting",
        char: "🤮"
    }, {
        name: "face_with_open_mouth_vomiting",
        char: "🤮"
    }, {
        name: "exploding_head",
        char: "🤯"
    }, {
        name: "shocked_face_with_exploding_head",
        char: "🤯"
    }, {
        name: "pregnant_woman",
        char: "🤰"
    }, {
        name: "breast-feeding",
        char: "🤱"
    }, {
        name: "palms_up_together",
        char: "🤲"
    }, {
        name: "selfie",
        char: "🤳"
    }, {
        name: "prince",
        char: "🤴"
    }, {
        name: "man_in_tuxedo",
        char: "🤵"
    }, {
        name: "mrs_claus",
        char: "🤶"
    }, {
        name: "mother_christmas",
        char: "🤶"
    }, {
        name: "woman-shrugging",
        char: "🤷‍♀️"
    }, {
        name: "man-shrugging",
        char: "🤷‍♂️"
    }, {
        name: "shrug",
        char: "🤷"
    }, {
        name: "woman-cartwheeling",
        char: "🤸‍♀️"
    }, {
        name: "man-cartwheeling",
        char: "🤸‍♂️"
    }, {
        name: "person_doing_cartwheel",
        char: "🤸"
    }, {
        name: "woman-juggling",
        char: "🤹‍♀️"
    }, {
        name: "man-juggling",
        char: "🤹‍♂️"
    }, {
        name: "juggling",
        char: "🤹"
    }, {
        name: "fencer",
        char: "🤺"
    }, {
        name: "woman-wrestling",
        char: "🤼‍♀️"
    }, {
        name: "man-wrestling",
        char: "🤼‍♂️"
    }, {
        name: "wrestlers",
        char: "🤼"
    }, {
        name: "woman-playing-water-polo",
        char: "🤽‍♀️"
    }, {
        name: "man-playing-water-polo",
        char: "🤽‍♂️"
    }, {
        name: "water_polo",
        char: "🤽"
    }, {
        name: "woman-playing-handball",
        char: "🤾‍♀️"
    }, {
        name: "man-playing-handball",
        char: "🤾‍♂️"
    }, {
        name: "handball",
        char: "🤾"
    }, {
        name: "wilted_flower",
        char: "🥀"
    }, {
        name: "drum_with_drumsticks",
        char: "🥁"
    }, {
        name: "clinking_glasses",
        char: "🥂"
    }, {
        name: "tumbler_glass",
        char: "🥃"
    }, {
        name: "spoon",
        char: "🥄"
    }, {
        name: "goal_net",
        char: "🥅"
    }, {
        name: "first_place_medal",
        char: "🥇"
    }, {
        name: "second_place_medal",
        char: "🥈"
    }, {
        name: "third_place_medal",
        char: "🥉"
    }, {
        name: "boxing_glove",
        char: "🥊"
    }, {
        name: "martial_arts_uniform",
        char: "🥋"
    }, {
        name: "curling_stone",
        char: "🥌"
    }, {
        name: "croissant",
        char: "🥐"
    }, {
        name: "avocado",
        char: "🥑"
    }, {
        name: "cucumber",
        char: "🥒"
    }, {
        name: "bacon",
        char: "🥓"
    }, {
        name: "potato",
        char: "🥔"
    }, {
        name: "carrot",
        char: "🥕"
    }, {
        name: "baguette_bread",
        char: "🥖"
    }, {
        name: "green_salad",
        char: "🥗"
    }, {
        name: "shallow_pan_of_food",
        char: "🥘"
    }, {
        name: "stuffed_flatbread",
        char: "🥙"
    }, {
        name: "egg",
        char: "🥚"
    }, {
        name: "glass_of_milk",
        char: "🥛"
    }, {
        name: "peanuts",
        char: "🥜"
    }, {
        name: "kiwifruit",
        char: "🥝"
    }, {
        name: "pancakes",
        char: "🥞"
    }, {
        name: "dumpling",
        char: "🥟"
    }, {
        name: "fortune_cookie",
        char: "🥠"
    }, {
        name: "takeout_box",
        char: "🥡"
    }, {
        name: "chopsticks",
        char: "🥢"
    }, {
        name: "bowl_with_spoon",
        char: "🥣"
    }, {
        name: "cup_with_straw",
        char: "🥤"
    }, {
        name: "coconut",
        char: "🥥"
    }, {
        name: "broccoli",
        char: "🥦"
    }, {
        name: "pie",
        char: "🥧"
    }, {
        name: "pretzel",
        char: "🥨"
    }, {
        name: "cut_of_meat",
        char: "🥩"
    }, {
        name: "sandwich",
        char: "🥪"
    }, {
        name: "canned_food",
        char: "🥫"
    }, {
        name: "crab",
        char: "🦀"
    }, {
        name: "lion_face",
        char: "🦁"
    }, {
        name: "scorpion",
        char: "🦂"
    }, {
        name: "turkey",
        char: "🦃"
    }, {
        name: "unicorn_face",
        char: "🦄"
    }, {
        name: "eagle",
        char: "🦅"
    }, {
        name: "duck",
        char: "🦆"
    }, {
        name: "bat",
        char: "🦇"
    }, {
        name: "shark",
        char: "🦈"
    }, {
        name: "owl",
        char: "🦉"
    }, {
        name: "fox_face",
        char: "🦊"
    }, {
        name: "butterfly",
        char: "🦋"
    }, {
        name: "deer",
        char: "🦌"
    }, {
        name: "gorilla",
        char: "🦍"
    }, {
        name: "lizard",
        char: "🦎"
    }, {
        name: "rhinoceros",
        char: "🦏"
    }, {
        name: "shrimp",
        char: "🦐"
    }, {
        name: "squid",
        char: "🦑"
    }, {
        name: "giraffe_face",
        char: "🦒"
    }, {
        name: "zebra_face",
        char: "🦓"
    }, {
        name: "hedgehog",
        char: "🦔"
    }, {
        name: "sauropod",
        char: "🦕"
    }, {
        name: "t-rex",
        char: "🦖"
    }, {
        name: "cricket",
        char: "🦗"
    }, {
        name: "cheese_wedge",
        char: "🧀"
    }, {
        name: "face_with_monocle",
        char: "🧐"
    }, {
        name: "adult",
        char: "🧑"
    }, {
        name: "child",
        char: "🧒"
    }, {
        name: "older_adult",
        char: "🧓"
    }, {
        name: "bearded_person",
        char: "🧔"
    }, {
        name: "person_with_headscarf",
        char: "🧕"
    }, {
        name: "woman_in_steamy_room",
        char: "🧖‍♀️"
    }, {
        name: "man_in_steamy_room",
        char: "🧖‍♂️"
    }, {
        name: "person_in_steamy_room",
        char: "🧖‍♂️"
    }, {
        name: "woman_climbing",
        char: "🧗‍♀️"
    }, {
        name: "person_climbing",
        char: "🧗‍♀️"
    }, {
        name: "man_climbing",
        char: "🧗‍♂️"
    }, {
        name: "woman_in_lotus_position",
        char: "🧘‍♀️"
    }, {
        name: "person_in_lotus_position",
        char: "🧘‍♀️"
    }, {
        name: "man_in_lotus_position",
        char: "🧘‍♂️"
    }, {
        name: "female_mage",
        char: "🧙‍♀️"
    }, {
        name: "mage",
        char: "🧙‍♀️"
    }, {
        name: "male_mage",
        char: "🧙‍♂️"
    }, {
        name: "female_fairy",
        char: "🧚‍♀️"
    }, {
        name: "fairy",
        char: "🧚‍♀️"
    }, {
        name: "male_fairy",
        char: "🧚‍♂️"
    }, {
        name: "female_vampire",
        char: "🧛‍♀️"
    }, {
        name: "vampire",
        char: "🧛‍♀️"
    }, {
        name: "male_vampire",
        char: "🧛‍♂️"
    }, {
        name: "mermaid",
        char: "🧜‍♀️"
    }, {
        name: "merman",
        char: "🧜‍♂️"
    }, {
        name: "merperson",
        char: "🧜‍♂️"
    }, {
        name: "female_elf",
        char: "🧝‍♀️"
    }, {
        name: "male_elf",
        char: "🧝‍♂️"
    }, {
        name: "elf",
        char: "🧝‍♂️"
    }, {
        name: "female_genie",
        char: "🧞‍♀️"
    }, {
        name: "male_genie",
        char: "🧞‍♂️"
    }, {
        name: "genie",
        char: "🧞‍♂️"
    }, {
        name: "female_zombie",
        char: "🧟‍♀️"
    }, {
        name: "male_zombie",
        char: "🧟‍♂️"
    }, {
        name: "zombie",
        char: "🧟‍♂️"
    }, {
        name: "brain",
        char: "🧠"
    }, {
        name: "orange_heart",
        char: "🧡"
    }, {
        name: "billed_cap",
        char: "🧢"
    }, {
        name: "scarf",
        char: "🧣"
    }, {
        name: "gloves",
        char: "🧤"
    }, {
        name: "coat",
        char: "🧥"
    }, {
        name: "socks",
        char: "🧦"
    }, {
        name: "bangbang",
        char: "‼️"
    }, {
        name: "interrobang",
        char: "⁉️"
    }, {
        name: "tm",
        char: "™️"
    }, {
        name: "information_source",
        char: "ℹ️"
    }, {
        name: "left_right_arrow",
        char: "↔️"
    }, {
        name: "arrow_up_down",
        char: "↕️"
    }, {
        name: "arrow_upper_left",
        char: "↖️"
    }, {
        name: "arrow_upper_right",
        char: "↗️"
    }, {
        name: "arrow_lower_right",
        char: "↘️"
    }, {
        name: "arrow_lower_left",
        char: "↙️"
    }, {
        name: "leftwards_arrow_with_hook",
        char: "↩️"
    }, {
        name: "arrow_right_hook",
        char: "↪️"
    }, {
        name: "watch",
        char: "⌚"
    }, {
        name: "hourglass",
        char: "⌛"
    }, {
        name: "keyboard",
        char: "⌨️"
    }, {
        name: "eject",
        char: "⏏️"
    }, {
        name: "fast_forward",
        char: "⏩"
    }, {
        name: "rewind",
        char: "⏪"
    }, {
        name: "arrow_double_up",
        char: "⏫"
    }, {
        name: "arrow_double_down",
        char: "⏬"
    }, {
        name: "black_right_pointing_double_triangle_with_vertical_bar",
        char: "⏭️"
    }, {
        name: "black_left_pointing_double_triangle_with_vertical_bar",
        char: "⏮️"
    }, {
        name: "black_right_pointing_triangle_with_double_vertical_bar",
        char: "⏯️"
    }, {
        name: "alarm_clock",
        char: "⏰"
    }, {
        name: "stopwatch",
        char: "⏱️"
    }, {
        name: "timer_clock",
        char: "⏲️"
    }, {
        name: "hourglass_flowing_sand",
        char: "⏳"
    }, {
        name: "double_vertical_bar",
        char: "⏸️"
    }, {
        name: "black_square_for_stop",
        char: "⏹️"
    }, {
        name: "black_circle_for_record",
        char: "⏺️"
    }, {
        name: "m",
        char: "Ⓜ️"
    }, {
        name: "black_small_square",
        char: "▪️"
    }, {
        name: "white_small_square",
        char: "▫️"
    }, {
        name: "arrow_forward",
        char: "▶️"
    }, {
        name: "arrow_backward",
        char: "◀️"
    }, {
        name: "white_medium_square",
        char: "◻️"
    }, {
        name: "black_medium_square",
        char: "◼️"
    }, {
        name: "white_medium_small_square",
        char: "◽"
    }, {
        name: "black_medium_small_square",
        char: "◾"
    }, {
        name: "sunny",
        char: "☀️"
    }, {
        name: "cloud",
        char: "☁️"
    }, {
        name: "umbrella",
        char: "☂️"
    }, {
        name: "snowman",
        char: "☃️"
    }, {
        name: "comet",
        char: "☄️"
    }, {
        name: "phone",
        char: "☎️"
    }, {
        name: "telephone",
        char: "☎️"
    }, {
        name: "ballot_box_with_check",
        char: "☑️"
    }, {
        name: "shamrock",
        char: "☘️"
    }, {
        name: "point_up",
        char: "☝️"
    }, {
        name: "skull_and_crossbones",
        char: "☠️"
    }, {
        name: "radioactive_sign",
        char: "☢️"
    }, {
        name: "biohazard_sign",
        char: "☣️"
    }, {
        name: "orthodox_cross",
        char: "☦️"
    }, {
        name: "star_and_crescent",
        char: "☪️"
    }, {
        name: "peace_symbol",
        char: "☮️"
    }, {
        name: "yin_yang",
        char: "☯️"
    }, {
        name: "wheel_of_dharma",
        char: "☸️"
    }, {
        name: "white_frowning_face",
        char: "☹️"
    }, {
        name: "relaxed",
        char: "☺️"
    }, {
        name: "female_sign",
        char: "♀️"
    }, {
        name: "male_sign",
        char: "♂️"
    }, {
        name: "gemini",
        char: "♊"
    }, {
        name: "cancer",
        char: "♋"
    }, {
        name: "leo",
        char: "♌"
    }, {
        name: "virgo",
        char: "♍"
    }, {
        name: "libra",
        char: "♎"
    }, {
        name: "scorpius",
        char: "♏"
    }, {
        name: "spades",
        char: "♠️"
    }, {
        name: "clubs",
        char: "♣️"
    }, {
        name: "hearts",
        char: "♥️"
    }, {
        name: "diamonds",
        char: "♦️"
    }, {
        name: "hotsprings",
        char: "♨️"
    }, {
        name: "recycle",
        char: "♻️"
    }, {
        name: "wheelchair",
        char: "♿"
    }, {
        name: "hammer_and_pick",
        char: "⚒️"
    }, {
        name: "crossed_swords",
        char: "⚔️"
    }, {
        name: "medical_symbol",
        char: "⚕️"
    }, {
        name: "staff_of_aesculapius",
        char: "⚕️"
    }, {
        name: "scales",
        char: "⚖️"
    }, {
        name: "alembic",
        char: "⚗️"
    }, {
        name: "gear",
        char: "⚙️"
    }, {
        name: "atom_symbol",
        char: "⚛️"
    }, {
        name: "fleur_de_lis",
        char: "⚜️"
    }, {
        name: "warning",
        char: "⚠️"
    }, {
        name: "zap",
        char: "⚡"
    }, {
        name: "white_circle",
        char: "⚪"
    }, {
        name: "black_circle",
        char: "⚫"
    }, {
        name: "coffin",
        char: "⚰️"
    }, {
        name: "funeral_urn",
        char: "⚱️"
    }, {
        name: "soccer",
        char: "⚽"
    }, {
        name: "baseball",
        char: "⚾"
    }, {
        name: "snowman_without_snow",
        char: "⛄"
    }, {
        name: "partly_sunny",
        char: "⛅"
    }, {
        name: "thunder_cloud_and_rain",
        char: "⛈️"
    }, {
        name: "ophiuchus",
        char: "⛎"
    }, {
        name: "pick",
        char: "⛏️"
    }, {
        name: "helmet_with_white_cross",
        char: "⛑️"
    }, {
        name: "chains",
        char: "⛓️"
    }, {
        name: "no_entry",
        char: "⛔"
    }, {
        name: "shinto_shrine",
        char: "⛩️"
    }, {
        name: "church",
        char: "⛪"
    }, {
        name: "mountain",
        char: "⛰️"
    }, {
        name: "umbrella_on_ground",
        char: "⛱️"
    }, {
        name: "fountain",
        char: "⛲"
    }, {
        name: "golf",
        char: "⛳"
    }, {
        name: "ferry",
        char: "⛴️"
    }, {
        name: "boat",
        char: "⛵"
    }, {
        name: "sailboat",
        char: "⛵"
    }, {
        name: "skier",
        char: "⛷️"
    }, {
        name: "ice_skate",
        char: "⛸️"
    }, {
        name: "woman-bouncing-ball",
        char: "⛹️‍♀️"
    }, {
        name: "man-bouncing-ball",
        char: "⛹️‍♂️"
    }, {
        name: "person_with_ball",
        char: "⛹️‍♂️"
    }, {
        name: "tent",
        char: "⛺"
    }, {
        name: "fuelpump",
        char: "⛽"
    }, {
        name: "scissors",
        char: "✂️"
    }, {
        name: "airplane",
        char: "✈️"
    }, {
        name: "envelope",
        char: "✉️"
    }, {
        name: "fist",
        char: "✊"
    }, {
        name: "hand",
        char: "✋"
    }, {
        name: "raised_hand",
        char: "✋"
    }, {
        name: "v",
        char: "✌️"
    }, {
        name: "writing_hand",
        char: "✍️"
    }, {
        name: "pencil2",
        char: "✏️"
    }, {
        name: "black_nib",
        char: "✒️"
    }, {
        name: "heavy_check_mark",
        char: "✔️"
    }, {
        name: "heavy_multiplication_x",
        char: "✖️"
    }, {
        name: "latin_cross",
        char: "✝️"
    }, {
        name: "star_of_david",
        char: "✡️"
    }, {
        name: "eight_spoked_asterisk",
        char: "✳️"
    }, {
        name: "eight_pointed_black_star",
        char: "✴️"
    }, {
        name: "snowflake",
        char: "❄️"
    }, {
        name: "sparkle",
        char: "❇️"
    }, {
        name: "x",
        char: "❌"
    }, {
        name: "negative_squared_cross_mark",
        char: "❎"
    }, {
        name: "heavy_heart_exclamation_mark_ornament",
        char: "❣️"
    }, {
        name: "heart",
        char: "❤️"
    }, {
        name: "arrow_right",
        char: "➡️"
    }, {
        name: "curly_loop",
        char: "➰"
    }, {
        name: "loop",
        char: "➿"
    }, {
        name: "arrow_heading_up",
        char: "⤴️"
    }, {
        name: "arrow_heading_down",
        char: "⤵️"
    }, {
        name: "arrow_left",
        char: "⬅️"
    }, {
        name: "arrow_up",
        char: "⬆️"
    }, {
        name: "arrow_down",
        char: "⬇️"
    }, {
        name: "black_large_square",
        char: "⬛"
    }, {
        name: "white_large_square",
        char: "⬜"
    }, {
        name: "star",
        char: "⭐"
    }, {
        name: "o",
        char: "⭕"
    }, {
        name: "wavy_dash",
        char: "〰️"
    }, {
        name: "part_alternation_mark",
        char: "〽️"
    }, {
        name: "congratulations",
        char: "㊗️"
    }, {
        name: "secret",
        char: "㊙️"
    }
];